// Generates a per-worktree docker compose OVERRIDE that caps each container's
// RAM. We never edit the user's compose file; instead the provisioner writes
// `COMPOSE_FILE=<original>:docker-compose.cl.yml` into the worktree's `.env`, so
// every `docker compose ...` invocation in that worktree (including the project's
// own `make run`) automatically merges this override and inherits the caps.
//
// Output is hand-emitted YAML for a fixed, trivial shape (services → mem_limit),
// which keeps this dependency-free (the repo has no YAML library). `mem_limit` is
// honored by `docker compose up` outside swarm mode.

import type { ComposeServiceSpec } from "./recipe-schema";

/** The override filename the provisioner writes into each worktree. */
export const OVERRIDE_FILENAME = "docker-compose.cl.yml";

/**
 * Build the override YAML from the recipe's container specs. Returns null when no
 * container declares a memLimit (nothing to override → don't write a file).
 */
export function buildComposeOverride(
  containers: ComposeServiceSpec[] | undefined,
  composeProject: string
): string | null {
  const capped = (containers ?? []).filter((c) => c.memLimit && c.name);
  if (capped.length === 0) {
    return null;
  }

  const lines: string[] = [
    `# ${OVERRIDE_FILENAME} — generated by Claude Luxure for worktree "${composeProject}".`,
    `# Per-worktree RAM caps. Do not edit by hand; regenerated on each provision.`,
    `# Merged automatically via COMPOSE_FILE in this worktree's .env.`,
    `services:`,
  ];
  for (const c of capped) {
    lines.push(`  ${c.name}:`);
    lines.push(`    mem_limit: ${c.memLimit!.trim()}`);
  }
  return lines.join("\n") + "\n";
}

/** Service names to start in a lean run: those not explicitly `essential: false`.
 *  Returns null when nothing is classified (→ start the whole stack). */
export function leanServiceNames(containers: ComposeServiceSpec[] | undefined): string[] | null {
  if (!containers || containers.length === 0) {
    return null;
  }
  const essential = containers.filter((c) => c.essential !== false).map((c) => c.name);
  // If every container is essential there's nothing to trim — start everything.
  return essential.length === containers.length ? null : essential;
}
